---
title: Olá, Blogdown!
author: Bruno
date: '2018-03-25'
slug: ola-blogdown
categories:
  - R
tags:
  - blogdown
---

Eu comecei este site por causa do pacote blogdown. Este pacote permite que que você escreva um documento em RMarkdown e faça o upload dele para um site diretamente do RStudio. Qual a graça disso? Vamos começar do começo.

[RMarkdown](https://rmarkdown.rstudio.com/) é um tipo de documento que permite que você junte texto (incluindo equações) e código de R num mesmo lugar. Você abre o RStudio, carrega seus dados, roda umas regressões, plota uns gráficos, descreve os resultados, e tudo vira um relatório 100% reprodutível[^1]. O relatório pode ser compilado como um arquivo .pdf, .html ou mesmo argh, .doc. Então, nunca mais esse negócio de gerar gráficos no R, exportar para um .jpeg, abrir o Word ou similar, e copiar manualmente[^2]. Em um Rmarkdown, tudo acontece no mesmo lugar. Bem conveniente.

O que o pacote blogdown faz é levar isso para a internet. Você pode montar um site inteiro com RMarkdown, mas vamos focar em um blog. Você tem uma ideia, escreve um post em Markdown, dá uns dois ou três cliques, e isto vai parar no seu blog online. Bem conveniente ao quadrado. 

Exceto por um pequeno problema. Não é tão fácil assim fazer todas as configurações necessárias para deixar tudo pronto para esses dois ou três cliques acontecerem. Se você não tem a mínima ideia de como um site funciona (assim como eu), ler o manual do [blogdown](https://bookdown.org/yihui/blogdown/) só vai te desencorajar (como me desencorajou por um bom tempo). O que aconteceu comigo foi ter topado por acaso em um [tutorial](https://www.youtube.com/watch?v=syWAKaj-4ck) no Youtube. 

A seguir, vou resumir rapidamente como funciona todo o processo, supondo um conhecimento básico de R e tendo o RStudio instalado. A ideia não é fazer um tutorial detalhado, mas sim explicar como as coisas se encaixam. Após ler o post, veja o vídeo para os detalhes e mão na massa. Em cada um dos passos vou deixar um link com mais informações. 

# Preliminares

O resumo da história é o seguinte. Você usa o RStudio e o pacote blogdown para montar seus posts (e outras páginas do site), escrevendo documentos em RMarkdown. O pacote blogdown faz uma primeira mágica, transformando seus arquivos RMarkdown em um site bonitinho através do Hugo. O que é Hugo? É um *static site generator*, basicamente um aplicativo pra gerar um monte de arquivos html que vão ser colocados online em algum lugar. Existem vários templates prontos; quando você gera o site através do blogdown, você tem a opção de escolher o template que mais lhe agrada. Essa primeira mágica já deixa o site prontinho; inclusive você pode visualizar ele dentro do RStudio. Vamos em frente.

O segunda mágica é colocar tudo online. Para isso, vamos fazer o upload do site para o [GitHub](www.github.com). O que é GiHub? É um serviço de hospedagem de projetos que usam controle de versão [Git](https://git-scm.com/). Quer saber mais sobre controle de versão e Git? [Aqui](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control) e [Aqui](https://ourcodingclub.github.io/2017/02/27/git.html). Você precisa saber sobre controle de versão? Não! Pense somente que este é o lugar para onde aqueles dois, três cliques dentro do RStudio vão mandar o site. O seu site hospedado no Github vai estar ligado ao [Netlify](https://www.netlify.com/), um serviço que implanta sites estáticos, e é onde as pessoas vão acessar o seu site. A segunda mágica então é essa: os dois, três cliques irão mandar a página para o GitHub, onde o Netlify automagicamente irá ler qualquer alteração que você fizer (um post novo por exemplo) e hospedará o blog. 

Este é um resumo tosco do processo. Não é exatamente o que acontece, mas se alguém tivesse me explicado desta maneira talvez eu tivesse feito este blog antes. 

Então vamos precisar de:

* RStudio e o pacote blogdown instalado;
* Uma conta no Github e o Git instalado;
* Uma conta no Netlify. 

# Passo 1: Git e Github


Git é um software para controle de versão, e GitHub um serviço de hospedagem para projetos colaborativos que usam Git. *Happy Git and GitHub for the useR* é um tutorial detalhado de como usar Git/GitHub e RStudio. 

1. Instale Git para [Windows](https://gitforwindows.org/)
2. Faça uma conta no [Github](https://github.com/) 
3. Configure o RStudio, lendo o capítulo 8 do [HappyGit](http://happygitwithr.com/hello-git.html)
4. Vá ao GitHub e crie um repositório, por exemplo `bdown`. Ele ficará hospedado em www.github.com/seu_user_name/bdown. 
5. Inicie um projeto novo no RStudio com controle de versão. Não sabe para que servem projetos no RStudio? Pare tudo e leia [aqui](http://r4ds.had.co.nz/workflow-projects.html). Isto é mais importante que montar um blog! Continuando, na configuração do projeto, coloque o link do seu repositório do GitHub.


# Passo 2: Blogdown

1. Instale o pacote blogdown usando `install.packages("blogdown")`, ou indo em *Tools* -> *Install Packages ...*   

2. Agora vem a parte trabalhosa. Crie seu site! O blogdown tem um comando chamado `new_site()`. Este comando criará toda a estrutura de um site, com alguns posts de exemplo, e usando o template `lithium`, o mesmo que utilizo aqui. Todo o seu site offline ficará na pasta `\content`. Crie novos posts com `new_post()`, ou utilizando o Addin *New Post*. Utilize `serve_site()` para compilar o site e visualizá-lo no Viewer - também disponível como Addin. O seu site ficará na pasta `\public`.    

3. Mande o site para o Github. Vá em *Tools* -> *Version Control*, selecione todas as mudanças e clique em *commit*. Depois clique em *Pull* para mandar para o GitHub. Neste passo provavelmente eu deveria explicar melhor o que é controle de versão e como ele funciona. Veja o vídeo tutorial e leia o HappyGit para entender melhor como isso funciona. 

# Passo 3: Netlify

Agora que o site está no seu repositório do GitHub, vamos conectá-lo ao Netlify. 

1. Crie uma conta no [Netlify](https://www.netlify.com/) usando seu usuário do Github. 

2. Clique em *New Site from Git*. Depois selecione *GitHub*. Selecione o repositório que contém o site, e no campo *Publish Directory* escreva `Public`, que é a pasta onde consta o site pronto para publicação. 

3. Pronto. Seu site está online, no endereço www.nome_aleatorio_com_numeros.netlify.com. Clique na opção para mudar o nome do site para algo como www.meu_nome.netlify.com. Caso você queira investir, compre um domínio do Google e link o netlify para seu domínio www.meu_nome.com. 

# Atualizando o site

Toda vez que você quiser fazer um post siga estes passos:

1. Abra o projeto do RStudio.
2. Crie um post com `new_post()`
3. Compile o site com `serve_site()`
4. Commit e Push o site para o GitHub.

Pronto, o Netlify irá ler as mudanças no GitHub. 

Gostaria de explicar muito mais coisas neste post, mas na verdade eu ainda não entendo metade das coisas que estão acontecendo. Espero que o post sirva ao menos para esclarecer de uma maneira geral como funciona. 


[^1]: Mais sobre pesquisa reprodutível [aqui](http://ropensci.github.io/reproducibility-guide/sections/introduction/).
[^2]: Rmarkdown também não é a solução para tudo. Se você estiver fazendo um documento mais complexo - uma tese ou dissertação por exemplo, com 99% de chance de isto ser feito em Latex - uma opção é salvar todos os seus outputs do R em uma pasta e ler todos a partir do seu .tex. Um próximo post talvez fale sobre o pacote **book**down e como escrever livros com Rmarkdown. 

